#!/bin/bash
curl http://localhost:7456/ && echo ''
curl http://localhost:7456/!all && echo ''
curl http://localhost:7456/foo && echo ''
curl -X POST http://localhost:7456/foo -d 'method=PUT' && echo ''
curl http://localhost:7456/ && echo ''
curl http://localhost:7456/foo && echo ''
curl http://localhost:7456/!all && echo ''
curl http://localhost:7456/foo/!all && echo '' 
curl http://localhost:7456/foo/bar && echo ''
curl -X POST http://localhost:7456/foo/bar -d 'method=PUT' && echo ''
curl http://localhost:7456/foo && echo '' 
curl http://localhost:7456/foo/!all && echo '' 
curl http://localhost:7456/foo/bar && echo ''
curl http://localhost:7456/foo/bar/qux && echo ''
curl -X POST http://localhost:7456/foo/bar/qux -d 'method=PUT&x=10&y=hello' && echo ''
curl http://localhost:7456/foo/bar/qux && echo ''
curl http://localhost:7456/foo/bar/!changes && echo ''
curl -X POST http://localhost:7456/foo/bar/baz -d 'method=PUT&x=19&y=text' && echo ''
curl http://localhost:7456/foo/bar/!changes && echo ''
curl -X POST http://localhost:7456/foo/bar/qux -d 'method=PUT&x=20&y=world' && echo ''
curl http://localhost:7456/foo/bar/!changes && echo ''
curl http://localhost:7456/foo/bar/qux && echo ''
curl -X POST http://localhost:7456/foo/bar/qux -d 'method=DELETE' && echo ''
curl http://localhost:7456/foo/bar/!changes && echo ''
curl http://localhost:7456/foo/bar/qux && echo ''
curl -X POST http://localhost:7456/foo/bar -d 'method=DELETE' && echo ''
curl http://localhost:7456/foo && echo '' 
curl http://localhost:7456/foo/!all && echo '' 
curl http://localhost:7456/foo/bar && echo ''
curl -X POST http://localhost:7456/foo -d 'method=DELETE' && echo ''
curl http://localhost:7456/foo && echo ''
curl http://localhost:7456/!all && echo ''
